---
title: 错误边界
comment: false
editLink: false
prev: false
next: false
---

## 简介

在`React`
组件树中,如果某个子组件抛出异常,默认情况下会导致整个组件树崩溃,此时用户就会看到类似下面这样的页面:

![](https://cdn.jsdelivr.net/gh/hhypygy/picx-images-hosting@master/image.6t6v693zvk.png)

这个页面会使用户不知所措,为了解决这个问题,`React`在`16`
版本中引入了[`错误边界(Error Boundary)`](https://react.dev/reference/react/Component#catching-rendering-errors-with-an-error-boundary)
的概念.

:::tip

`错误边界`是一个特殊的组件,它可以捕获发生在其子组件树中任何位置的`JavaScript`错误,并且渲染出备用的UI,而不是崩溃的页面.这将大大提高用户体验.

:::

## 捕获组件树中的错误

先来模拟一下因为子组件抛出异常导致整个组件树崩溃的情况:

::: sandpack#react-ts React 示例 [  theme=dark]

@file /App.tsx

```tsx 
 import React, {useState} from 'react';

const MaybeThrow = (props) => {
    throw new Error('示例错误')


    return (<></>);
};


export default () => {
    const [clicked, setClicked] = useState(false)
    return (
        <>
            <button onClick={() => setClicked(true)}>点击抛出错误</button>
            {clicked && <MaybeThrow/>}
        </>
    );
}
``` 

:::

现在我们用[react-error-boundary](https://www.npmjs.com/package/react-error-boundary)[^react-error-boundary]
库中的`ErrorBoundary`
组件来捕获这个错误,并渲染出备用的UI:

```tsx
//App.tsx
import {ErrorBoundary} from 'react-error-boundary';

export default () => {
    const myErrorHandler = (error: Error, info: React.ErrorInfo) => {
        alert('捕获到了错误');
        return false;
    };
    return (
        <>
            <ErrorBoundary
                FallbackComponent={() => <h1>出现错误了</h1>}
                onError={myErrorHandler}
            >
                <MaybeThrow/>
            </ErrorBoundary>
        </>
    );
};

```

<iframe
src="https://stackblitz.com/edit/vitejs-vite-5atafb?ctl=1&embed=1&file=src%2FApp.tsx&hideNavigation=1&theme=dark"
style="width:100%; height:500px; border:0; border-radius: 4px; overflow:hidden;"
> </iframe>

## 无法捕获的错误

`ErrorBoundary`可以捕获大部分的错误,但有一些特定类型的错误是它捕获不了的,包括:

### 事件处理器内部的错误

<iframe src="https://stackblitz.com/edit/vitejs-vite-594rm8?ctl=1&embed=1&file=src%2FApp.tsx"
style="width:100%; height:500px; border:0; border-radius: 4px; overflow:hidden;"
> </iframe>

在上面的例子中,虽然用`ErrorBoundary`包裹了`MaybeThrow`组件

```tsx
<ErrorBoundary
    FallbackComponent={() => <h1>出现错误了</h1>}
    onError={myErrorHandler}
>
    <MaybeThrow/>
</ErrorBoundary>
```

但是在按钮`<button onClick={handleClick}>点击我</button>`的`onClick`事件处理函数中抛出的异常是无法被`ErrorBoundary`捕获的

:::tip
这种虽然因为没有被`ErrorBoundary`捕获到而不显示备用UI,但也不会导致整个组件树崩溃,因为错误不是在渲染期间抛出的,而是在事件处理器内部抛出的,此时组件树已经渲染完成,只是事件无法得到正确的响应
:::

[^react-error-boundary]: react-error-boundary

    这个库是`React`官方推荐的错误边界库,它提供了一个`ErrorBoundary`组件,用于以简单和一致的方式来处理`React`应用中的错误边界

### 异步代码中的错误

`ErrorBoundary`无法捕获`setTimeout`、原生`Promises`或者其他异步API的错误,这些错误和`事件处理器内部的错误`
的表现一样,不显示备用UI,但也不会导致整个组件树崩溃

### 服务端渲染期间的错误

这个很好理解,错误发生在`SSR`服务器端,自然也不会被`ErrorBoundary`捕获到

## 异步加载的组件

`Suspense`是为了让组件可以等待某些异步操作的完成,并在等待的时候显示一个备用的UI(
比如在等待整个页面渲染的过程中显示一个骨架屏)

对于使用`React.lazy`和`Suspense`异步加载的组件,首先要明确一点:

:::info Suspense的机制
它在渲染备用UI的时候是因为需要在等待主UI加载,此时是一种正常的`等待`行为,抛出的是`Promise rejection`,而不是`Error`
,不应该也不会被`ErrorBoundary`
捕获

但是如果主UI在渲染的时候抛出了错误,仍然会被`ErrorBoundary`捕获到
:::

<iframe src="https://stackblitz.com/edit/vitejs-vite-unsfar?ctl=1&embed=1&file=src%2FApp.tsx"
style="width:100%; height:500px; border:0; border-radius: 4px; overflow:hidden;"
> </iframe>

### `react-router-dom`

`react-router-dom`在处理异步组件时,已经实现了自己的错误处理机制,可能会在错误到达`ErrorBoundary`之前就处理掉错误

<iframe src="https://stackblitz.com/edit/vitejs-vite-wuvvph?ctl=1&embed=1&file=src%2FApp.tsx"
style="width:100%; height:500px; border:0; border-radius: 4px; overflow:hidden;"
> </iframe>

由于错误被`react-router-dom`处理了,因此显示的是`react-router-dom`提供的备用UI,而不是`ErrorBoundary`提供的备用UI

![](https://cdn.jsdelivr.net/gh/hhypygy/picx-images-hosting@master/image.6t6v693zvk.png)

通过使用`ErrorBoundary`包裹`Suspense`组件来解决这个问题:

```tsx
// ...

const router = createBrowserRouter(
  createRoutesFromElements(
    <Route
      path="/"
      element={
        <ErrorBoundary FallbackComponent={() => <h1>出现错误了</h1>} onError={myErrorHandler}>
          <Suspense fallback={<div>Loading...</div>}>
            <OtherComponent />
          </Suspense>
        </ErrorBoundary>
      }
    ></Route>
  )
);

// ...
```
